---
name: Build and Deploy AMI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: "17"
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*',
            '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Tests
        run: gradle test
      - name: Build JAR
        run: gradle build
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: webapp-jar
          path: build/libs/*.jar
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Download JAR Artifact
        uses: actions/download-artifact@v3
        with:
          name: webapp-jar
      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install Packer
        run: >
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -

          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

          sudo apt-get update && sudo apt-get install packer
      - name: Deploy AMI with Packer
        run: >
          packer build -var 'artifact_url=https://github.com/${{ github.repository
          }}/actions/artifacts/${{ steps.download.outputs.artifact-path
          }}/webapp-jar' \

          -var 'db_name=${{ secrets.DB_NAME }}' \

          -var 'db_username=${{ secrets.DB_USERNAME }}' \

          -var 'db_password=${{ secrets.DB_PASSWORD }}' \

          packer/main.pkr.hcl
