---
name: Packer Status Check
on:
  pull_request:
    branches:
      - main
jobs:
  packer-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Packer
        run: >
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -

          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

          sudo apt-get update && sudo apt-get install packer
      - name: Initialize Packer
        run: |
          cd packer/
          packer init main.pkr.hcl
      - name: Run packer fmt
        run: |
          cd packer/
          packer fmt -check -diff main.pkr.hcl
        continue-on-error: false
      - name: Run packer validate
        run: |
          cd packer/
          packer validate \
            -var "artifact_path=/tmp/test.jar" \
            -var "db_name=test_db" \
            -var "db_username=test_user" \
            -var "db_password=test_password" \
            -var "instance_type=t2.micro" \
            main.pkr.hcl
        continue-on-error: false
